"""Export helpers for slide decks."""

"""angelas part"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path


def slide_deck_to_pptx_bytes(slide_deck: dict) -> bytes:
    from pptx import Presentation
    from pptx.util import Inches, Pt

    def _image_dimensions(path: str) -> tuple[int, int] | None:
        try:
            from PIL import Image as PILImage
        except ModuleNotFoundError:
            return None

        try:
            with PILImage.open(path) as image:
                return image.size
        except Exception:
            return None

    def _add_picture_fit(slide, image_path: str, left, top, box_width, box_height) -> bool:
        if not image_path or not Path(image_path).exists():
            return False

        dimensions = _image_dimensions(image_path)
        if not dimensions:
            try:
                slide.shapes.add_picture(image_path, left, top, width=box_width)
                return True
            except Exception:
                return False

        width_px, height_px = dimensions
        if width_px <= 0 or height_px <= 0:
            return False

        image_ratio = width_px / height_px
        box_ratio = box_width / box_height

        if image_ratio >= box_ratio:
            target_width = box_width
            target_height = int(box_width / image_ratio)
        else:
            target_height = box_height
            target_width = int(box_height * image_ratio)

        left_offset = int((box_width - target_width) / 2)
        top_offset = int((box_height - target_height) / 2)

        try:
            slide.shapes.add_picture(
                image_path,
                left + left_offset,
                top + top_offset,
                width=target_width,
                height=target_height,
            )
            return True
        except Exception:
            return False

    image_lookup = {
        item.get("image_id"): item
        for item in slide_deck.get("image_catalog", [])
        if item.get("image_id")
    }

    presentation = Presentation()

    title_slide_layout = presentation.slide_layouts[0]
    bullet_layout = presentation.slide_layouts[1]

    title_slide = presentation.slides.add_slide(title_slide_layout)
    title_slide.shapes.title.text = slide_deck.get("title", "Presentation")
    subtitle = title_slide.placeholders[1]
    subtitle.text = "Generated by Smart Teacher Assistant"

    for item in slide_deck.get("slides", []):
        slide = presentation.slides.add_slide(bullet_layout)
        slide.shapes.title.text = item.get("slide_title", "Slide")

        body_shape = slide.shapes.placeholders[1]
        image_refs = [
            ref for ref in item.get("image_refs", [])
            if ref in image_lookup and image_lookup[ref].get("asset_path")
        ][:2]

        if image_refs:
            body_shape.width = Inches(5.5)

        body = body_shape.text_frame
        body.clear()

        bullets = item.get("bullets", [])
        for index, bullet in enumerate(bullets):
            paragraph = body.paragraphs[0] if index == 0 else body.add_paragraph()
            paragraph.text = bullet
            paragraph.level = 0
            paragraph.font.size = Pt(22)

        if image_refs:
            image_left = Inches(7.0)
            image_top = Inches(1.8)
            image_box_width = Inches(2.6)
            image_box_height = Inches(4.8 / max(len(image_refs), 1))

            for index, image_id in enumerate(image_refs):
                image_path = image_lookup[image_id]["asset_path"]
                top = int(image_top + (image_box_height * index))
                _add_picture_fit(slide, image_path, int(image_left), top, int(image_box_width), int(image_box_height))

        speaker_notes = (item.get("speaker_notes") or "").strip()
        if speaker_notes:
            notes_slide = slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = speaker_notes

    buffer = BytesIO()
    presentation.save(buffer)
    return buffer.getvalue()
